version: '3'
services:
  sidspec-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidspec-streamlit
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: streamlitsidspec.wanglab.science
      VIRTUAL_PORT: 8501
      LETSENCRYPT_HOST: streamlitsidspec.wanglab.science
      LETSENCRYPT_EMAIL: siddhant.poojary@ucr.edu
networks:
  nginx-net:
    external:
      name: nginx-net
